apiVersion: v1
kind: Service
metadata:
  name: node
  namespace: myapp
spec:
  selector:
    app: node
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: myapp
spec:
  selector:
    app: django
  type: ClusterIP
  ports:
  - port: 8000
