apiVersion: v1
kind: ConfigMap
metadata:
  name: example
  namespace: nginx
data:
  default.conf: |
    server {
        listen       80;
        server_name  example.com;

        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }
    }