
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent
        name: nginx
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
          # subPath: default.conf
      securityContext:
        sysctls:
        - name: "net.ipv4.tcp_keepalive_time"
          value: "300"
      volumes:
      - name: nginx-config-volume
        projected:
          sources:
          - configMap:
              name: default
          - configMap:
              name: example
